export const pallets = {
  background: '#FAFAFF',
  black: '#050505',
  border: '#E8E8E8',
  card: '#F3F3F7',
  darkGrey: '#BDBDBD',
  grey: '#F6F6F6',
  grey2: '#666666',
  inactive: '#E3E3E3',
  notification: '#FFCCCC',
  primary: '#FFCCCC',
  red: '#FF0058',
  text: '#0B0B0B',
  transparent: 'transparent',
  white: '#FFFFFF',
};
